/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "f1tenth",
            "endpoint": "https://2s2tvxfs9h.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "races-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "teams-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "maps-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "images-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "users-staging",
            "region": "us-east-1"
        },
        {
            "tableName": "evaluations-staging",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "mapimages233412-staging",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b9309e16-1cc2-415e-888a-37d7d62b2e59",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_42bGpdDBN",
    "aws_user_pools_web_client_id": "65gvoc6idc86cbma940slolk6e",
    "oauth": {}
};


export default awsmobile;
